GET http://localhost:5000/students

###
GET http://localhost:5000/students/1

### 
POST http://localhost:5000/students
Content-Type: application/json

{
    "name": "Devan",
    "nim": "031",
    "email": "dev@gmail.com",
    "major": "Computer Science",
    "university": "Universitas Brawijaya"
}

###
PATCH http://localhost:5000/students/1
Content-Type: application/json

{
    "name": "Devan",
    "nim": "031",
    "email": "dev@gmail.com",
    "major": "Informatics",
    "university": "Universitas Brawijaya"
}

###
DELETE  http://localhost:5000/students/1

